---
# tasks file for serverspec

- name: upload serverspecs
  synchronize:
    src: ../../../tests
    dest: "{{ serverspec_tests_path }}"
    recursive: yes
    delete: yes
  when: serverspec_install_bundler|bool and serverspec_upload_folder|bool
  tags:
    - serverspec

- name: upload marathon runtime serverspecs
  template:
    src: marathon_runtime_spec.rb.j2
    dest: "{{ serverspec_tests_path }}/tests/spec/marathon/marathon_runtime_spec.rb"
    mode: 0755
  sudo: yes
  when: serverspec_upload_folder|bool
  tags:
    - serverspec

- name: install bundler
  sudo: yes
  command: gem install bundler --no-ri --no-rdoc
  args:
    creates: /usr/local/bin/bundler
  when: serverspec_install_bundler|bool
  tags:
    - serverspec

- name: install bundle files
  sudo: yes
  command: bundle install --path vendor
  args:
    chdir: "{{ serverspec_tests_path }}/tests"
    creates: "{{ serverspec_tests_path }}/tests/vendor"
  tags:
    - serverspec

- name: run serverspec tests
  sudo: yes
  command: "bundle exec rake serverspec:{{ test_role }}"
  args:
    chdir: "{{ serverspec_tests_path }}/tests"
  when: test_role is defined
  tags:
    - serverspec
