---
# tasks file for serverspec

- name: upload serverspecs
  synchronize:
    src: ../../../tests
    dest: "{{ serverspec_tests_path }}"
    recursive: yes
    delete: yes
  when: serverspec_run_tests and serverspec_install_bundler and serverspec_upload_folder
  tags:
    - serverspec

- name: install bundler
  command: gem install bundler --no-ri --no-rdoc
  args:
    creates: /usr/local/bin/bundler
  when: serverspec_run_tests and serverspec_install_bundler
  tags:
    - serverspec

- name: install bundle files
  command: bundle install --path vendor
  args:
    chdir: "{{ serverspec_tests_path }}/tests"
    creates: "{{ serverspec_tests_path }}/tests/vendor"
  when: serverspec_run_tests
  tags:
    - serverspec

- name: run serverspec tests
  sudo: yes
  command: "bundle exec rake serverspec:{{ test_role }}"
  args:
    chdir: "{{ serverspec_tests_path }}/tests"
  when: test_role is defined and serverspec_run_tests
  tags:
    - serverspec
