---
- hosts: all:!bastion
  gather_facts: no
  tasks:
    - name: Wait for ssh port to become available from bastion server.
      wait_for:
        port: "{{ ansible_ssh_port }}"
        host: "{{ ansible_ssh_host }}"
        delay: 10
        timeout: 60
      delegate_to: "{{ bastion_ip }}"
      sudo: False
      when: bastion_ip is defined
    - name: Wait for port 22 to become available from local server.
      local_action: "wait_for port={{ ansible_ssh_port }} host={{ ansible_ssh_host }} delay=10 timeout=60"
      sudo: False
      when: bastion_ip is not defined

- hosts: all
  tasks:
    - name: set hostname to local ipv4 address
      sudo: Yes
      lineinfile:
        dest: /etc/hosts
        line: "{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }}"
  roles:
    - consul
    - docker
    - weave
    - dnsmasq

- hosts: all:!bastion
  roles:
    - registrator
    - cadvisor
    - { role: prometheus, when: prometheus_enabled|bool }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- hosts: mesos_masters
  roles:
    - zookeeper
    - { role: mesos_docker, mesos_install_mode: "master", tags: ["mesos_masters"] }
    - { role: marathon, tags: ["marathon"] }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- hosts: mesos_slaves_docker
  roles:
    - { role: mesos_docker, mesos_install_mode: "slave", tags: ["mesos_slaves"] }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- hosts: elasticsearch
  roles:
    - { role: elasticsearch, tags: ["elasticsearch"] }

- hosts: all:!bastion
  pre_tasks:
    - name: remove datadog.override
      file:
        path: /etc/init/datadog-agent.override
        state: absent
  roles:
    - { role: datadog-agent, tags: ["monitoring"] }

- hosts: all:!bastion:!elasticsearch
  roles:
    - { role: monitored, tags: ["monitoring"] }

- hosts: load_balancers
  roles:
    - { role: haproxy, tags: ["haproxy"] }
  serial: 1
  environment:
    DOCKER_HOST: "{{ docker_host }}"

# Installing DCOS frameworks and apps from one master.
- hosts: mesos_masters
  roles:
    - { role: dcos_cli, tags: ["apps"] }
  vars_files:
    - roles/prometheus/defaults/main.yml
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- include: tests/test.yml
  vars_files:
    - ../roles/marathon/defaults/main.yml

- include: contrib-plugins/playbook.yml
