---
- hosts: all:!role=bastion
  gather_facts: false
  vars:
    ansible_python_interpreter: "PATH=/home/core/bin:$PATH python"
  tasks:
    - name: Wait for ssh port to become available from bastion server.
      wait_for:
        port: "{{ ansible_port }}"
        host: "{{ ansible_host }}"
        delay: 10
        timeout: 180
      delegate_to: "{{ bastion_ip }}"
      become: false
      when: bastion_ip is defined
    - name: Wait for port 22 to become available from local server.
      local_action: "wait_for port={{ ansible_port }} host={{ ansible_host }} delay=10 timeout=180"
      become: false
      when: bastion_ip is not defined


- include: playbooks/coreos-bootstrap.yml

- hosts: all
  tasks: []

- hosts: all:!role=bastion
  roles:
    - docker
    - weave
    - consul
    # @todo - fix vault integration with coreOS
    #- vault

- hosts: all:!role=bastion
  roles:
    - { role: cadvisor, when: cadvisor_enabled|bool }
    - { role: prometheus, when: prometheus_enabled|bool }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- hosts: mesos_masters
  roles:
    - zookeeper
    - { role: mesos, mesos_install_mode: "master" }
    - mesos_consul
    - { role: marathon, when: marathon_enabled|bool }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- hosts: mesos_agents
  roles:
    - { role: mesos, mesos_install_mode: "agent" }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- hosts: load_balancers
  roles:
    - { role: traefik, tags: ["traefik"] }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

# Installing DCOS frameworks and apps from one master.
- include: dcos.yml

- hosts: log_servers
  roles:
    - { role: logstash, when: elk_enabled|bool }
  environment:
    DOCKER_HOST: "{{ docker_host }}"

- include: contrib-plugins/playbook.yml
