---
- hosts: all
  roles:
    - dnsmasq
    - consul

- hosts: mesos_masters
  vars:
    consul_is_server: true
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }
    - zookeeper
    - marathon

- hosts: mesos_slaves
  roles:
    - docker
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }
    - weave
    - registrator

- hosts: load_balancers
  roles:
    - docker
    - weave
    - registrator
    - haproxy

- include: tests/test.yml
