---
- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for port 22 to become available from bastion server.
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 10
        timeout: 60
      delegate_to: "{{ nat_ip }}"
      sudo: False
      when: PROVIDER == 'aws' or PROVIDER == 'AWS'

    - name: Wait for port 22 to become available from local server.
      local_action: "wait_for port=22 host={{ inventory_hostname }} delay=10 timeout=60"
      sudo: False
      when: PROVIDER != 'aws' and PROVIDER != 'AWS'

- hosts: all
  roles:
    - dnsmasq
    - consul
    - docker
    - weave
    - registrator

- hosts: mesos_masters
  vars:
    consul_is_server: true
  roles:
    - { role: mesos, mesos_install_mode: "master", tags: ["mesos-master"] }
    - zookeeper
    - marathon

- hosts: mesos_slaves
  roles:
    - { role: mesos, mesos_install_mode: "slave", tags: ["mesos-slave"] }

- hosts: load_balancers
  roles:
    - haproxy

- include: tests/test.yml
