#!/bin/bash

DIGITALOCEAN_REGION=${DIGITALOCEAN_REGION:-lon1}
DIGITALOCEAN_SSH_KEY=${DIGITALOCEAN_SSH_KEY:?"Need to set DIGITALOCEAN_SSH_KEY non-empty"}
DIGITALOCEAN_SSH_FINGERPRINT=${DIGITALOCEAN_SSH_FINGERPRINT:?"Need to set DIGITALOCEAN_SSH_FINGERPRINT non-empty"}
DIGITALOCEAN_API_TOKEN=${DIGITALOCEAN_API_TOKEN:?"Need to set DIGITALOCEAN_API_TOKEN non-empty"}
DO_CLIENT_ID=${DO_CLIENT_ID:?"Need to set DO_CLIENT_ID non-empty"}
DO_API_KEY=${DO_API_KEY:?"Need to set DO_API_KEY non-empty"}

ATLAS_TOKEN=${ATLAS_TOKEN:?"Need to set ATLAS_TOKEN non-empty"}
ATLAS_INFRASTRUCTURE=${ATLAS_INFRASTRUCTURE:-apollo/infrastructure}
MASTER_SIZE=${MASTER_SIZE:-512mb}
SLAVE_SIZE=${SLAVE_SIZE:-512mb}
NUM_SLAVES=${NUM_SLAVES:-1}
MASTER_IMAGE=${MASTER_IMAGE:-11147507}
SLAVE_IMAGE=${SLAVE_IMAGE:-11147507}
