#!/bin/bash

DIGITALOCEAN_SSH_FINGERPRINT=${SSH_FINGERPRINT}
DIGITALOCEAN_SSH_KEY=~/.ssh/digital_ocean

DIGITALOCEAN_REGION=${DIGITALOCEAN_REGION:-lon1}
DIGITALOCEAN_SSH_KEY=${DIGITALOCEAN_SSH_KEY:?"Need to set DIGITALOCEAN_SSH_KEY non-empty"}
DIGITALOCEAN_SSH_FINGERPRINT=${DIGITALOCEAN_SSH_FINGERPRINT:?"Need to set DIGITALOCEAN_SSH_FINGERPRINT non-empty"}
DIGITALOCEAN_API_TOKEN=${DIGITALOCEAN_API_TOKEN:?"Need to set DIGITALOCEAN_SSH_FINGERPRINT non-empty"}

ATLAS_TOKEN=${ATLAS_TOKEN:?"Need to set ATLAS_TOKEN non-empty"}
ATLAS_INFRASTRUCTURE=${ATLAS_INFRASTRUCTURE:-capgemini/infrastructure}
MASTER_SIZE=${MASTER_SIZE:-512mb}
SLAVE_SIZE=${SLAVE_SIZE:-512mb}
NUM_SLAVES=${NUM_SLAVES:-1}
