---
# handlers file for consul
- name: wait for consul to listen
  wait_for:
    host: "{{ consul_bind_addr }}"
    port: 8500

- name: restart consul
  sudo: yes
  command: systemctl restart consul
  notify:
    - wait for consul to listen
