---
# handlers file for consul
- name: wait for consul to listen
  wait_for:
    host: "{{ consul_bind_addr }}"
    port: 8500

- name: restart consul
  become: yes
  service:
    name: consul
    state: restarted
  notify:
    - wait for consul to listen
