---
# handlers file for dnsmasq
- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  sudo: yes

- name: Reload dnsmasq
  service:
    name: dnsmasq
    state: reloaded
  sudo: yes
