---
# handlers file for zookeeper
- name: restart zookeeper
  service:
    name: zookeeper
    state: restarted
  become: yes

- name: start zookeeper
  service:
    name: zookeeper
    state: started
  become: yes
