- name: download scope
  become: yes
  become_user: root
  get_url:
    url: "{{ scope_url }}"
    dest: "{{ scope_bin }}"
    mode: 0755
    validate_certs: no
    force: true
  environment: "{{ proxy_env }}"
  tags:
    - scope

- name: deploy scope service
  become: yes
  become_user: root
  template:
    src: scope.service.j2
    dest: /etc/systemd/system/scope.service
  tags:
    - scope

- name: ensure scope service is running.
  become: yes
  service:
    name: scope
    state: started
    enabled: yes
  tags:
    - scope
