---
# handlers file for marathon
- name: restart marathon
  sudo: yes
  service:
    name: marathon
    state: restarted
  sudo: yes
  notify:
    - wait for marathon to listen

- name: wait for marathon to listen
  command: /usr/local/bin/marathon-wait-for-listen.sh
