---
# tasks file for frameworks
- include_vars: "{{ item }}.yml"
  with_items:
    - "{{ frameworks_list }}"

- name: "create config directory"
  when: "frameworks_{{ item }}_enabled | bool"
  run_once: true
  template:
    src: "{{ item }}-config.j2"
    dest: "/tmp/{{ item }}-config"
    mode: 0755
  sudo: yes
  tags:
    - "{{ item }}"
  with_items:
    - "{{ frameworks_list }}"

- name: "install dcos-cli package"
  when: "frameworks_{{ item }}_enabled | bool"
  run_once: true
  docker:
    name: "{{ item }}"
    image: "{{ frameworks_dcos_cli_image }}"
    state: started
    command: "package install --options=/config --yes {{ item }}"
    volumes:
    - "/tmp/{{ item }}-config:/config"
    env:
      MESOS_MASTER_URL: "{{ frameworks_mesos_master_url }}"
      MARATHON_URL: "{{ frameworks_marathon_url }}"
      SOURCES: "{{ frameworks_sources }}"
  tags:
    - "{{ item }}"
  with_items:
    - "{{ frameworks_list }}"

- name: "uninstall dcos-cli package"
  when: "not frameworks_{{ item }}_enabled | bool"
  run_once: true
  docker:
    name: "{{ item }}"
    image: "{{ frameworks_dcos_cli_image }}"
    state: started
    command: "package uninstall {{ item }}"
    env:
      MESOS_MASTER_URL: "{{ frameworks_mesos_master_url }}"
      MARATHON_URL: "{{ frameworks_marathon_url }}"
  tags:
    - "{{ item }}"
  with_items:
    - "{{ frameworks_list }}"

